In [76]:
import numpy as np #is used for scientific calculation

In [77]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array ([1,2,3,4,5,6,7,8,9,10])
# arr = np.array(lst)

In [78]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [81]:
lst[1]

2

In [82]:
arr[2] + lst[1]

np.int64(5)

In [83]:
lst1 = [1,2,3]
lst2 = [4,5,6]
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [84]:
[1,2,3] + [4,5,6,7]

[1, 2, 3, 4, 5, 6, 7]

In [85]:
lst1 + lst2

[1, 2, 3, 4, 5, 6]

In [86]:
arr1 + arr2

array([5, 7, 9])

In [87]:
len(lst1)

3

In [88]:
len(arr1)

3

In [89]:
list_mat = [
    [1,2,3,4,5],
    [4,5,6,5,5], 
    [7,8,9,6,9],
    [10,11,12,7,10]
]

len(list_mat), len(list_mat[0])
list_mat

[[1, 2, 3, 4, 5], [4, 5, 6, 5, 5], [7, 8, 9, 6, 9], [10, 11, 12, 7, 10]]

In [90]:
np.array(list_mat)

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  5,  5],
       [ 7,  8,  9,  6,  9],
       [10, 11, 12,  7, 10]])

In [91]:
list_mat

[[1, 2, 3, 4, 5], [4, 5, 6, 5, 5], [7, 8, 9, 6, 9], [10, 11, 12, 7, 10]]

In [92]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
matrix_array = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6],[10,11,12,7],[1,2,3,4]])
matrix_array

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  6],
       [10, 11, 12,  7],
       [ 1,  2,  3,  4]])

In [94]:
matrix_array.shape

(5, 4)

In [95]:
#three_d_tensor = np.array()
scalar = np.array(5) #0d tensor
vector = np.array ([1,2,3]) #1d tensor
matrix = np.array([[1,2],[3,4],[5,6]]) # 2d tensor

In [101]:
print(f'Scalar dimensions: {scalar.ndim}')
print(f'Vector dimensions: {vector.ndim}')
print(f'Matrix dimensions: {matrix.ndim}')

Scalar dimensions: 0
Vector dimensions: 1
Matrix dimensions: 2


In [96]:
vector.ndim

1

In [97]:
matrix.ndim

2

In [98]:
threed_tensor = np.array([
    [[1,2,3],
      [4,5,6],
      [4,5,6]],
    
    [[11,12,13],
     [14,15,16],
    [4,5,6], ],
    
    # [[21,22,23],
    #   [24,25,26]],
])
# (2,2,3)
threed_tensor.shape

(2, 3, 3)

In [99]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16],
        [ 4,  5,  6]]])

In [103]:
threed_tensor.ndim

3

In [100]:
matrix_array.shape

(5, 4)

In [64]:
vector.ndim

1

In [65]:
matrix.ndim

2

In [66]:
threed_tensor = np.array([
    [[1,2,3],
     [4,5,6],
     [4,5,6]],
    [[11,12,13],
     [14,25,26],
     [4,5,6], ],
    #[[21,22,23],
    # [24,25,26]],
])
# (2,2,3)
threed_tensor.shape

(2, 3, 3)

In [67]:
lst = [[1,"how", True, 3.14], 'Helo', 1]

In [68]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 25, 26],
        [ 4,  5,  6]]])

In [69]:
threed_tensor.ndim

3

In [70]:
#Data types
np.int64

numpy.int64

In [71]:
np.int64

numpy.int64

In [104]:
np.uint8(129)
# int - int8, int16, int32, int64, uint8, uint16, unit32, unit64
# 0000 0000
#1111 1111
# 1 0000 0000 

2**64

18446744073709551616

In [ ]:
# -128 -> 127
# 0 -> 255

In [ ]:
bin(256)

'0b100000000'

In [105]:
np.uint8(255)

np.uint8(255)

In [ ]:
int('11111111',2)
# 1 0 0
# 4 2 1
128 + 64 + 32 + 16 + 8 + 4 + 2 + 1
0b11111111

255

In [ ]:
 2**64

18446744073709551616

In [ ]:
# np.float16 -> np.float128

In [106]:
np.float64(2.1)

np.float64(2.1)

In [107]:
np.uint8(256)

OverflowError: Python integer 256 out of bounds for uint8

In [108]:
arr = np.array([1,2,3,4,5, 127], dtype=np.int8)

In [110]:
arr.dtype

dtype('int8')

In [111]:
arr

array([  1,   2,   3,   4,   5, 127], dtype=int8)

In [115]:
arr = np.array([1, "Hello"])
arr + arr

array(['11', 'HelloHello'], dtype='<U42')

In [113]:
int('42')

42

In [120]:
mat = np.array([[1,2], [3,4], [5,6]])
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
    '''
           0  1
    0 -> [ 1, 2 ]
    1 -> [ 3, 4 ]
    2 -> [ 5, 6 ]
    
    '''

'\n       0  1\n0 -> [ 1, 2 ]\n1 -> [ 3, 4 ]\n2 -> [ 5, 6 ]\n\n'

In [122]:
mat[1,0]

np.int64(3)

In [123]:
mat.shape

(3, 2)

In [125]:
mat[0,0]

np.int64(1)

In [126]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16],
        [ 4,  5,  6]]])

In [127]:
threed_tensor = np.array([
    [ # 0
    
    # 0   1  2
     [ 1, 2, 3], #0
     [ 4, 5, 6], #1
     [ 24,25,26] #2
    ],
    [ # 1
    # 0   1  2
     [ 11,12,13], #0
     [ 14,15,16], #1
     [ 34,35,36]  #2
     
    ],
    # [[21,22,23],
    # 24,25,26]],
])
# (2,3,3)
threed_tensor.shape

(2, 3, 3)

In [130]:
threed_tensor[1, : , 2:]

array([[13],
       [16],
       [36]])

In [128]:
threed_tensor[0, 1, 2]

np.int64(6)

In [129]:
threed_tensor.ndim

3