In [ ]:
import numpy as np #is used for scientific calculation

In [7]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array ([1,2,3,4,5,6,7,8,9,10])

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
lst[1]

2

In [12]:
arr[2] + lst[1]

np.int64(5)

In [16]:
lst1 = [1,2,3]
lst2 = [4,5,6]
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [17]:
lst1 + lst2

[1, 2, 3, 4, 5, 6]

In [18]:
arr1 + arr2

array([5, 7, 9])

In [19]:
len(lst1)

3

In [24]:
len(arr1)

3

In [26]:
list_mat = [
    [1,2,3,4],
    [4,5,6,5], 
    [7,8,9,6],
    [10,11,12,7]
]

len(list_mat), len(list_mat[0])

(4, 4)

In [27]:
list_mat

[[1, 2, 3, 4], [4, 5, 6, 5], [7, 8, 9, 6], [10, 11, 12, 7]]

In [28]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
matrix_array = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6],[10,11,12,7]])
matrix_array

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  6],
       [10, 11, 12,  7]])

In [30]:
matrix_array.shape

(4, 4)

In [31]:
#three_d_tensor = np.array()
vector = np.array ([1,2,3]) #1d tensor
matrix = np.array([[1,2],[3,4],[5,6]]) # 2d tensor

In [32]:
vector.ndim

1

In [33]:
matrix.ndim

2

In [39]:
threed_tensor = np.array([
    [
        [
            1,2,3
        ],
        
        [4,5,6]
    ],
    
    [
        [11,12,13],
        
        [14,15,16]
    ]
])

#(2,2,3)
threed_tensor.shape

(2, 2, 3)

In [40]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [41]:
matrix_array.shape

(4, 4)

In [ ]:
#three_d_tensor = np.array()
scalar = np.array(5) # 0d tensor
vector = np.array([1,2,3]) #1d tensor
matrix = np.array([[1,2],[3,4],[5,6]]) #2d tensor

In [46]:
print(f'Scalar dimensions: {scalar.ndim}')
print(f'Vector dimensions: {vector.ndim}')
print(f'Matrix dimensions: {matrix.ndim}')

Scalar dimensions: 0
Vector dimensions: 1
Matrix dimensions: 2


In [47]:
# Data Types
np.int64

numpy.int64

In [ ]:
np.int8 